name: Docker Compose CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      message:
        description: 'The flow has been triggered manually'
        required: false
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH Connection
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Remote Server to known_hosts
      run: echo ${{vars.PUBLIC_KEY}} >> .ssh/known_hosts  

    - name: Log into Remote Server
      run: ssh ${{vars.REMOTE_USER }}@${{vars.REMOTE_SERVER}} 'cd /home/ec2-user/BirthdayBuddy && git pull'

    - name: Run Docker Compose
      run: ssh username@remote-server 'cd /home/ec2-user/BirthdayBuddy && docker-compose up -d'