name: Docker Compose CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      message:
        description: 'The flow has been triggered manually'
        required: false

env:
  REMOTE_SERVER: ec2-52-57-22-132.eu-central-1.compute.amazonaws.com
  REMOTE_USER: ec2-user
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SSH-Compose
        # You may pin to the exact commit or the version.
        # uses: matiasnu/github-action-ssh-docker-compose@d2e13949c92cb86a69ea36e83ebaa01d6d01de9c
        uses: matiasnu/github-action-ssh-docker-compose@v2.0.1
        with:
          # Private SSH key used for logging into remote system.
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # Remote host name.
          ssh_host: $REMOTE_SERVER
          
          # Remote SSH port.
          ssh_port: 22 # default is 22
          
          # Remote user name.
          ssh_user: $REMOTE_USER
          
          # Prefix for docker-compose containers.
          docker_compose_prefix:  cicd
          
          # Docker compose file to use
          docker_compose_filename: docker-compose.yml
          
          # Use docker stack instead of docker compose ("true" or "false").
          use_stack: false # optional, default is false
          
          # Execute docker-compose-down ("true" or "false").
          docker_compose_down: false # optional, default is false
