name: Docker Compose CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      message:
        description: 'The flow has been triggered manually'
        required: false

env:
  REMOTE_SERVER: ec2-52-57-22-132.eu-central-1.compute.amazonaws.com
  REMOTE_USER: ec2-user
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH Connection
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Log into Remote Server
      run: ssh $REMOTE_USER@$REMOTE_SERVER 'cd /home/ec2-user/cicd/BirthdayBuddy && touch README
      
    - name: Log into Remote Server
      run: ssh $REMOTE_USER@$REMOTE_SERVER 'cd /home/ec2-user/cicd/BirthdayBuddy && git pull'

    - name: Run Docker Compose
      run: ssh username@remote-server 'cd /home/ec2-user/cicd/BirthdayBuddy && docker-compose up -d'


